/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rjcc;

/**
 *
 * @author jonick
 */
public class DJournalSettings extends javax.swing.JDialog {

    /**
     * Creates new form DJournalSettings
     */
    JPL jpl;
    public DJournalSettings(java.awt.Frame parent, boolean modal, JPL jpl) {
        super(parent, modal);        
        this.jpl = jpl;
        initComponents();
        jCheckBox1.setSelected(jpl.getAuto());
        jCheckBox2.setSelected(jpl.getNumber());
        jCheckBox5.setSelected(jpl.getDriver());
        jCheckBox3.setSelected(jpl.getDateStart());
        jCheckBox4.setSelected(jpl.getDateStop());
        jCheckBox6.setSelected(jpl.getOdoStart());
        jCheckBox7.setSelected(jpl.getOdoStop());
        jCheckBox8.setSelected(jpl.getGsmStart());
        jCheckBox9.setSelected(jpl.getGsmStop());
        jCheckBox10.setSelected(jpl.getGsmGet());
        jCheckBox11.setSelected(jpl.getSpecStart());
        jCheckBox12.setSelected(jpl.getSpecStop());
        jCheckBox13.setSelected(jpl.getUser());
        jCheckBox14.setSelected(jpl.getDes());
        jCheckBox15.setSelected(jpl.getShift());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Настройки журнала");
        setResizable(false);

        jToolBar1.setRollover(true);

        jButton1.setText("Сохранить");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("Отмена");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jCheckBox1.setText("Автомобиль");
        jCheckBox1.setFocusPainted(false);
        jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxuncheck.png"))); // NOI18N
        jCheckBox1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxcheck.png"))); // NOI18N

        jCheckBox2.setText("Гос номер");
        jCheckBox2.setFocusPainted(false);
        jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxuncheck.png"))); // NOI18N
        jCheckBox2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxcheck.png"))); // NOI18N

        jCheckBox3.setText("Дата выезда");
        jCheckBox3.setFocusPainted(false);
        jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxuncheck.png"))); // NOI18N
        jCheckBox3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxcheck.png"))); // NOI18N

        jCheckBox4.setText("Дата возвращения");
        jCheckBox4.setFocusPainted(false);
        jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxuncheck.png"))); // NOI18N
        jCheckBox4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxcheck.png"))); // NOI18N

        jCheckBox5.setText("Водитель");
        jCheckBox5.setFocusPainted(false);
        jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxuncheck.png"))); // NOI18N
        jCheckBox5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxcheck.png"))); // NOI18N

        jCheckBox6.setText("Спидометр выезда");
        jCheckBox6.setFocusPainted(false);
        jCheckBox6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxuncheck.png"))); // NOI18N
        jCheckBox6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxcheck.png"))); // NOI18N

        jCheckBox7.setText("Спидометр возврата");
        jCheckBox7.setFocusPainted(false);
        jCheckBox7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxuncheck.png"))); // NOI18N
        jCheckBox7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxcheck.png"))); // NOI18N

        jCheckBox8.setText("ГСМ выезда");
        jCheckBox8.setFocusPainted(false);
        jCheckBox8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxuncheck.png"))); // NOI18N
        jCheckBox8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxcheck.png"))); // NOI18N

        jCheckBox9.setText("ГСМ возврата");
        jCheckBox9.setFocusPainted(false);
        jCheckBox9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxuncheck.png"))); // NOI18N
        jCheckBox9.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxcheck.png"))); // NOI18N

        jCheckBox10.setText("Дозаправка");
        jCheckBox10.setFocusPainted(false);
        jCheckBox10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxuncheck.png"))); // NOI18N
        jCheckBox10.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxcheck.png"))); // NOI18N

        jCheckBox11.setText("Моточасы выезда");
        jCheckBox11.setFocusPainted(false);
        jCheckBox11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxuncheck.png"))); // NOI18N
        jCheckBox11.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxcheck.png"))); // NOI18N

        jCheckBox12.setText("Моточасы возврата");
        jCheckBox12.setFocusPainted(false);
        jCheckBox12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxuncheck.png"))); // NOI18N
        jCheckBox12.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxcheck.png"))); // NOI18N

        jCheckBox13.setText("Диспетчер");
        jCheckBox13.setFocusPainted(false);
        jCheckBox13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxuncheck.png"))); // NOI18N
        jCheckBox13.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxcheck.png"))); // NOI18N

        jCheckBox14.setText("Комментарий");
        jCheckBox14.setFocusPainted(false);
        jCheckBox14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxuncheck.png"))); // NOI18N
        jCheckBox14.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxcheck.png"))); // NOI18N

        jCheckBox15.setText("Смена");
        jCheckBox15.setFocusPainted(false);
        jCheckBox15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxuncheck.png"))); // NOI18N
        jCheckBox15.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/rjcc/checkboxcheck.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox14)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox15)
                    .addComponent(jCheckBox13))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox14)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jpl.setAuto(jCheckBox1.isSelected());
        jpl.setNumber(jCheckBox2.isSelected());
        jpl.setDriver(jCheckBox5.isSelected());
        jpl.setDateStart(jCheckBox3.isSelected());
        jpl.setDateStop(jCheckBox4.isSelected());
        jpl.setOdoStart(jCheckBox6.isSelected());
        jpl.setOdoStop(jCheckBox7.isSelected());
        jpl.setGsmStart(jCheckBox8.isSelected());
        jpl.setGsmStop(jCheckBox9.isSelected());
        jpl.setGsmGet(jCheckBox10.isSelected());
        jpl.setSpecStart(jCheckBox11.isSelected());
        jpl.setSpecStop(jCheckBox12.isSelected());
        jpl.setShift(jCheckBox15.isSelected());
        jpl.setUser(jCheckBox13.isSelected());
        jpl.setDes(jCheckBox14.isSelected());
        dispose();
        MainFrame.exec = true;
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
